linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - errorlint
    - prealloc
    - predeclared
    - protogetter
    - testifylint
    - zerologlint
    - copyloopvar
    - wrapcheck
    - perfsprint