version: 1
project_name: poutine

before:
  hooks:
    - go mod verify

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '7'

kos:
  - repository: ghcr.io/boostsecurityio/poutine
    base_image: 'cgr.dev/chainguard/git:latest@sha256:f06036ea97419c784339638cf4a21b52d39df8dfd8aa0e0e73307fc1082c6043'
    tags:
      - '{{.Version}}'
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

docker_signs:
  - artifacts: manifests
    args:
      - "sign"
      - "${artifact}"
      - "--yes" # skip user interaction

signs:
  - cmd: cosign
    certificate: '${artifact}.pem'
    args:
      - "sign-blob"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # skip user interaction
    artifacts: all
    output: true

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

brews:
- repository:
    owner: boostsecurityio
    name: homebrew-tap
    branch: main
    token: "{{ .Env.TAP_GITHUB_TOKEN }}"
  directory: Formula
  homepage: https://boostsecurity.io
  description: poutine - The Build Pipeline risk analyzer.
  license: Apache 2.0

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
