package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func page(payload interface{}) []byte {
	data, err := json.Marshal(map[string]interface{}{"payload": payload})
	if err != nil {
		panic(err)
	}
	return []byte(`<script type="application/json" data-target="react-app.embeddedData">` + string(data) + `</script>`)
}

func TestCollect(t *testing.T) {
	first := action{ID: 1, Slug: "setup-uv", Type: "repository_action", Verified: true, Owner: "astral-sh"}
	second := action{ID: 2, Slug: "dbt_semantics_to_sigma", Type: "repository_action", Verified: true, Owner: "sigma-computing"}
	urls := map[string][]byte{
		marketplace + "?type=actions&verification=verified_creator&query=sort%3Aname-asc&page=1": page(map[string]interface{}{
			"searchResults": searchResults{Results: []action{first}, Total: 2, TotalPages: 2},
		}),
		marketplace + "?type=actions&verification=verified_creator&query=sort%3Aname-asc&page=2": page(map[string]interface{}{
			"searchResults": searchResults{Results: []action{second}, Total: 2, TotalPages: 2},
		}),
		marketplace + "/actions/setup-uv":               page(map[string]interface{}{"action": first}),
		marketplace + "/actions/dbt_semantics_to_sigma": page(map[string]interface{}{"action": second}),
	}
	for _, test := range []struct {
		name string
		url  string
		data []byte
	}{
		{"complete", "", nil},
		{"structured search", marketplace + "?type=actions&verification=verified_creator&query=sort%3Aname-asc&page=1", []byte(`{"results":[{"id":1,"slug":"setup-uv","type":"repository_action","isVerifiedOwner":true}],"total":2,"totalPages":2}`)},
		{"missing JSON", marketplace + "?type=actions&verification=verified_creator&query=sort%3Aname-asc&page=2", []byte("error page")},
		{"duplicate page", marketplace + "?type=actions&verification=verified_creator&query=sort%3Aname-asc&page=2", urls[marketplace+"?type=actions&verification=verified_creator&query=sort%3Aname-asc&page=1"]},
		{"changing total", marketplace + "?type=actions&verification=verified_creator&query=sort%3Aname-asc&page=2", page(map[string]interface{}{
			"searchResults": searchResults{Results: []action{second}, Total: 3, TotalPages: 2},
		})},
		{"incomplete results", marketplace + "?type=actions&verification=verified_creator&query=sort%3Aname-asc&page=1", page(map[string]interface{}{
			"searchResults": searchResults{Results: []action{first}, Total: 2, TotalPages: 1},
		})},
		{"unverified detail", marketplace + "/actions/setup-uv", page(map[string]interface{}{
			"action": action{ID: 1, Slug: "setup-uv", Type: "repository_action", Owner: "astral-sh"},
		})},
		{"wrong action", marketplace + "/actions/setup-uv", urls[marketplace+"/actions/dbt_semantics_to_sigma"]},
		{"fetch failure", marketplace + "/actions/setup-uv", nil},
	} {
		t.Run(test.name, func(t *testing.T) {
			actions, err := collect(context.Background(), func(_ context.Context, url string) ([]byte, error) {
				if url == test.url {
					if test.data == nil {
						return nil, errors.New("HTTP 429")
					}
					return test.data, nil
				}
				data, ok := urls[url]
				if !ok {
					return nil, fmt.Errorf("unexpected URL: %s", url)
				}
				return data, nil
			})
			if test.name == "complete" || test.name == "structured search" {
				require.NoError(t, err)
				require.Equal(t, []action{first, second}, actions)
			} else {
				require.Error(t, err)
				require.Nil(t, actions)
			}
		})
	}
}

func TestSnapshotReplay(t *testing.T) {
	dir := t.TempDir()
	rule := filepath.Join(dir, "rule.rego")
	input := filepath.Join(dir, "snapshot.json")
	original := "package rules.example\n\ngithub_verified_partners contains p if some p in [\"old\"]\n\n# Consider input package namespaces as verified\ngithub_verified_partners contains input.packages[_].package_namespace\n"
	require.NoError(t, os.WriteFile(rule, []byte(original), 0644))
	actions := []action{
		{ID: 1, Slug: "uv", Type: "repository_action", Verified: true, Owner: "Astral-SH"},
		{ID: 2, Slug: "checkout", Type: "repository_action", Verified: true, Owner: "actions"},
		{ID: 3, Slug: "ruff", Type: "repository_action", Verified: true, Owner: "astral-sh"},
	}
	data, err := json.Marshal(sourceSnapshot{Total: len(actions), Actions: actions})
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(input, data, 0644))
	require.NoError(t, run(input, "", rule))
	updated, err := os.ReadFile(rule)
	require.NoError(t, err)
	require.Equal(t, strings.Replace(original, `["old"]`, `["actions", "astral-sh"]`, 1), string(updated))

	// Input order and repeat runs must not change the generated bytes.
	actions[0], actions[2] = actions[2], actions[0]
	data, err = json.Marshal(sourceSnapshot{Total: len(actions), Actions: actions})
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(input, data, 0644))
	require.NoError(t, run(input, "", rule))
	again, err := os.ReadFile(rule)
	require.NoError(t, err)
	require.Equal(t, updated, again)

	// Invalid snapshots must leave the existing rule untouched.
	for _, data := range []string{
		`{"total":0,"actions":[]}`,
		"not JSON",
		`{"total":2,"actions":[{"id":1,"slug":"uv","type":"repository_action","isVerifiedOwner":true,"ownerLogin":"astral-sh"}]}`,
		`{"total":1,"actions":[{"id":1,"slug":"uv","type":"repository_action","isVerifiedOwner":false,"ownerLogin":"astral-sh"}]}`,
	} {
		require.NoError(t, os.WriteFile(input, []byte(data), 0644))
		require.Error(t, run(input, "", rule))
		again, err := os.ReadFile(rule)
		require.NoError(t, err)
		require.Equal(t, updated, again)
	}
}

func TestFetchPageRateLimit(t *testing.T) {
	for _, recovers := range []bool{true, false} {
		t.Run(strconv.FormatBool(recovers), func(t *testing.T) {
			calls := 0
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				calls++
				if calls == 1 || !recovers {
					w.Header().Set("Retry-After", "0")
					w.WriteHeader(http.StatusTooManyRequests)
					return
				}
				fmt.Fprint(w, `{"payload":{"action":{"ownerLogin":"astral-sh"}}}`)
			}))
			defer server.Close()
			pace := make(chan time.Time)
			close(pace)
			data, err := fetchPage(context.Background(), server.Client(), server.URL, pace)
			if recovers {
				require.NoError(t, err)
				var result struct{ Action action }
				require.NoError(t, payload(data, &result))
				require.Equal(t, "astral-sh", result.Action.Owner)
				require.Equal(t, 2, calls)
			} else {
				require.Error(t, err)
				require.Nil(t, data)
				require.Equal(t, 3, calls)
			}
		})
	}
}
